### ISSUE TITLE
Request: Documentation on creating our own renodx mods?

### ISSUE THREAD

**Issue by CasualDev242** [clshortfuse/renodx#1]
I've successfully used the renodx-devkit addon to extract shaders from a game, and then replaced them with my custom ones.

However, I'm confused as to how I can then turn this into an addon, for a few reasons.

One is that they are CSO files that are output, rather than anything in .hlsl file extension that your mods all seem to use. 

The other is simply how to take my changed shaders, and bundle them into a project for usage in a game.

Perhaps some basic documentation on this, and perhaps an empty template that can be used for our results?

Thanks for all your great work.

**Comment by CasualDev242** [comment]
I'll take that as a no...

**Comment by clshortfuse** [comment]
Sorry, I hadn't seen this until today. You would need to decompile the cso files with something like https://github.com/bo3b/3Dmigoto/blob/master/HLSLDecompiler/cmd_Decompiler/cmd_Decompiler.cpp for FXC compiled shaders and https://github.com/HansKristian-Work/dxil-spirv with https://github.com/KhronosGroup/SPIRV-Cross for DXC compiled shaders.

You'd have to add an entry to the `cmakelist.txt` file once you add a folder to `/src/`  that has an `addon.cpp` file in it. The rest is just replicating the folder structure. The `cmakelist.txt` shows it looks for `*.ps_x_x.hlsl` and auto embeds them into `build/embed`. I'd imagine the Sea of Stars folder is simplest one to use as a basic for a template. I honestly just copy paste that folder and rename the title in `addon.cpp` file.

**Comment by clshortfuse** [comment]
Completed with [f36b7ac](https://github.com/clshortfuse/renodx/commit/f36b7ac7ecb59d2f68ec29706c81e5619dba74c8)
