### ISSUE TITLE
Reno addons on another games?

### ISSUE THREAD

**Issue by sysio93** [clshortfuse/renodx#38]
Hello, im was thinking about Addons on my reshade while updating , and findout i cant pick from list Reno addon, while reading hub im was fascinating about options which give your pretty  great addon.
Its be maybe in future more games got optimized for Reno? Exacly im was Guild Wars 2 player and really hard was get Optimize find to it.
Im just tryingout get realistic quality with stable fps on 4K HDR setup with 240hz refresh rate ;D

**Comment by Shadetail** [comment]
Here is the GW2 renodx addon (it's fantastic):
source: https://github.com/NotVoosh/renodx/tree/main/src/games
download: https://notvoosh.github.io/renodx/renodx-gw2.addon64

There's a thread for it on [HDR Den discord](https://discord.gg/QSKdcBtc):
https://discord.com/channels/1161035767917850784/1276006462224597062

**Comment by NotVoosh** [comment]
@marat569 started a list in Wiki:
https://github.com/clshortfuse/renodx/wiki/Mods

**Comment by clshortfuse** [comment]
Closing since we have a Wiki page
